version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=API_XJCO2913
      - MYSQL_USER=xiaofei
      - MYSQL_PASSWORD=2021110003
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./data/mysql:/var/lib/mysql