version: '3'

services:
  backend1:
    build:
      context: https://github.com/XJCO2913/API_Backend.git#main
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

  backend_test1:
    build:
      context: https://github.com/XJCO2913/API_Backend.git#develop
      dockerfile: Dockerfile
    ports:
      - 8099:8080
    depends_on:
      mysql:
        condition: service_healthy

  user_frontend:
    build:
      context: /home/lighthouse/Web_Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80
    volumes:
      - /home/lighthouse/Web_Frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: 'mysql:latest'
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=API_XJCO2913_TEST
      - MYSQL_USER=xiaofei
      - MYSQL_PASSWORD=2021110003
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass 2021110003
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/lighthouse/xjco2913/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/lighthouse/xjco2913/log:/var/log/nginx:rw
