server:
  live:
    port: "80"
  test:
    port: "8099"

database:
  mysql:
    host: "43.136.232.116"
    port: "3307"
    user: "xiaofei"
    password: "2021110003"
    databaseName: "API_XJCO2913_TEST"
  redis:
    host: "43.136.232.116"
    port: "6379"
    password: "2021110003"
    db: 0

jwt:
  secret: "Xbtxed0prpo7pxE42e"
