// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActivityUser = "activity_user"

// ActivityUser mapped from table <activity_user>
type ActivityUser struct {
	ActivityID string     `gorm:"column:activityId;primaryKey" json:"activityId"`
	UserID     string     `gorm:"column:userId;primaryKey" json:"userId"`
	CreatedAt  *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt  *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	FinalFee   int32      `gorm:"column:finalFee;not null" json:"finalFee"`
}

// TableName ActivityUser's table name
func (*ActivityUser) TableName() string {
	return TableNameActivityUser
}
