// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	CommentID string     `gorm:"column:commentId;primaryKey" json:"commentId"`
	AuthorID  string     `gorm:"column:authorId;not null" json:"authorId"`
	MomentID  string     `gorm:"column:momentId;not null" json:"momentId"`
	Content   string     `gorm:"column:content;not null" json:"content"`
	CreatedAt *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
