// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	UserID      string     `gorm:"column:userId;primaryKey" json:"userId"`
	FollowingID string     `gorm:"column:followingId;primaryKey" json:"followingId"`
	CreatedAt   *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt   *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
