// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLike = "likes"

// Like mapped from table <likes>
type Like struct {
	UserID    string     `gorm:"column:userId;primaryKey" json:"userId"`
	MomentID  string     `gorm:"column:momentId;primaryKey" json:"momentId"`
	CreatedAt *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Like's table name
func (*Like) TableName() string {
	return TableNameLike
}
