// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLog = "logs"

// Log mapped from table <logs>
type Log struct {
	ID        int32      `gorm:"column:ID;primaryKey;autoIncrement:true" json:"ID"`
	Msg       string     `gorm:"column:msg;not null" json:"msg"`
	Type      string     `gorm:"column:type;not null;comment:types: info, error, warning or SQL" json:"type"` // types: info, error, warning or SQL
	CreatedAt *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
