// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMoment = "moments"

// Moment mapped from table <moments>
type Moment struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AuthorID  string     `gorm:"column:authorId;not null" json:"authorId"`
	Content   *string    `gorm:"column:content" json:"content"`
	ImageURL  *string    `gorm:"column:imageUrl" json:"imageUrl"`
	VideoURL  *string    `gorm:"column:videoUrl" json:"videoUrl"`
	RouteID   *int32     `gorm:"column:routeId" json:"routeId"`
	CreatedAt *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Moment's table name
func (*Moment) TableName() string {
	return TableNameMoment
}
