// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganiser = "organisers"

// Organiser mapped from table <organisers>
type Organiser struct {
	ID     int32  `gorm:"column:ID;primaryKey;autoIncrement:true" json:"ID"`
	UserID string `gorm:"column:userId;not null" json:"userId"`
	Status int32  `gorm:"column:status;not null;comment:-1 is refused, 1 is untreated, 2 is agreed" json:"status"` // -1 is refused, 1 is untreated, 2 is agreed
}

// TableName Organiser's table name
func (*Organiser) TableName() string {
	return TableNameOrganiser
}
