// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID        int32      `gorm:"column:id;primaryKey" json:"id"`
	Name      string     `gorm:"column:name;not null" json:"name"`
	Price     int32      `gorm:"column:price;not null" json:"price"`
	CreatedAt *time.Time `gorm:"column:createdAt;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt *time.Time `gorm:"column:updatedAt;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
